DROP DATABASE IF EXISTS utkrusht_orders;
DROP ROLE IF EXISTS app_user;
CREATE ROLE app_user LOGIN;
CREATE DATABASE utkrusht_orders OWNER app_user;
\connect utkrusht_orders

CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    price NUMERIC(12,2) NOT NULL
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    status VARCHAR(32) NOT NULL,
    total_amount NUMERIC(12,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(12,2) NOT NULL
);

CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_status_created_at_id ON orders(status, created_at DESC, id DESC) INCLUDE (customer_id, total_amount);
CREATE INDEX idx_order_items_order_id ON order_items(order_id);
CREATE INDEX idx_order_items_product_id ON order_items(product_id);

INSERT INTO customers(id, email, full_name, created_at)
SELECT gs, 'customer' || gs || '@example.com', 'Customer ' || gs, now() - (gs || ' days')::interval
FROM generate_series(1, 80) gs;

INSERT INTO products(id, sku, name, price)
SELECT gs, 'SKU-' || lpad(gs::text, 4, '0'), 'Product ' || gs, (10 + (gs * 1.75))::numeric(12,2)
FROM generate_series(1, 30) gs;

INSERT INTO orders(id, customer_id, status, total_amount, created_at)
SELECT gs,
       ((gs - 1) % 80) + 1,
       CASE WHEN gs % 4 = 0 THEN 'CANCELLED' WHEN gs % 4 = 1 THEN 'PAID' WHEN gs % 4 = 2 THEN 'FULFILLED' ELSE 'PAID' END,
       0,
       now() - (gs || ' hours')::interval
FROM generate_series(1, 180) gs;

INSERT INTO order_items(order_id, product_id, quantity, unit_price)
SELECT o.id,
       ((o.id + item_no) % 30) + 1,
       ((o.id + item_no) % 3) + 1,
       p.price
FROM orders o
CROSS JOIN generate_series(1, 4) item_no
JOIN products p ON p.id = ((o.id + item_no) % 30) + 1;

UPDATE orders o
SET total_amount = totals.total
FROM (
    SELECT order_id, sum(quantity * unit_price)::numeric(12,2) AS total
    FROM order_items
    GROUP BY order_id
) totals
WHERE totals.order_id = o.id;

SELECT setval('customers_id_seq', (SELECT max(id) FROM customers));
SELECT setval('products_id_seq', (SELECT max(id) FROM products));
SELECT setval('orders_id_seq', (SELECT max(id) FROM orders));
SELECT setval('order_items_id_seq', (SELECT max(id) FROM order_items));

ALTER TABLE customers OWNER TO app_user;
ALTER TABLE products OWNER TO app_user;
ALTER TABLE orders OWNER TO app_user;
ALTER TABLE order_items OWNER TO app_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO app_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO app_user;
